luzdohorto/config/routes.rb
Rails.application.routes.draw do
  resources :colabs
  resources :colaboradors
  resources :instituicos
  get 'cont_users/index'
  get 'cont_users/new'
  get 'cont_users/edit'
  

  post 'savenew', to: 'users#savenew'
  
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  
  resources :cadastros

  resources :relatorios

  match 'download' => 'relatorios#download', via: [:get, :post]
  #post 'download'=> 'relatorios#download'


  root 'cadastros#index'

  #get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

luzdohorto/app/models/cadastro.rb
class Cadastro < ActiveRecord::Base
	belongs_to :user
	has_many :colabs
	paginates_per 20

	def self.assocCadColab (cadastro_id, colaborador_id)
  		colab = Colab.new
  		colab.cadastro_id = cadastro_id
  		colab.colaborador_id = colaborador_id
  		colab.save
  	end

  	def self.search(query, user)
    	if query.present? and user.role == "admin"
      		where(['id_cliente_coelce like :query OR
            	valor like :query OR livre like :query', query: "%#{query}%"])
    	elsif query.present?
    		where(:user_id => user.id).where(['id_cliente_coelce like :query OR
            	valor like :query ', query: "%#{query}%"])
    	elsif user.role == "admin"
    		all
    	else
    		where(:user_id => user.id)
    	end
    end
	
end

luzdohorto/app/controllers/cadastros_controller.rb
class CadastrosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_cadastro, only: [:show, :edit, :update, :destroy]
   
  # GET /cadastros
  # GET /cadastros.json
  def index

    @search_query = params[:q]
    
    @cadastros = Cadastro.order('created_at DESC').search(@search_query, current_user).page params[:page]
    # if params[:search]
    #   @cadastros = Cadastro.where("id_cliente_coelce like ?", "%#{params[:search]}")
    #   elsif :user_role == "admin"      
    #    @cadastros = Cadastro.joins(:user).order("created_at DESC").page params['page']
    #   else   
    #    @cadastros = Cadastro.where(:user_id => current_user.id).order("created_at DESC").page params['page']        
    # end
  end

  # GET /cadastros/1
  # GET /cadastros/1.json
  def show
  end

  # GET /cadastros/new
  def new
    @cadastro = current_user.cadastros.build
  end
  

  # GET /cadastros/1/edit
  def edit
  end

  # POST /cadastros
  # POST /cadastros.json
  def create
    @cadastro = current_user.cadastros.build(cadastro_params)
    
    respond_to do |format|
      if @cadastro.save
        Cadastro.assocCadColab(@cadastro.id, params[:colaborador][:colaborador_id])
        format.html { redirect_to @cadastro, notice: 'Cadastro criado com sucesso.' }
        format.json { render :show, status: :created, location: @cadastro }
           
      else
        format.html { render :new }
        format.json { render json: @cadastro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cadastros/1
  # PATCH/PUT /cadastros/1.json
  def update
    respond_to do |format|
      if @cadastro.update(cadastro_params)
        format.html { redirect_to @cadastro, notice: 'Cadastro atualizado com sucesso..' }
        format.json { render :show, status: :ok, location: @cadastro }
      else
        format.html { render :edit }
        format.json { render json: @cadastro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cadastros/1
  # DELETE /cadastros/1.json
  def destroy
    @cadastro.destroy
    respond_to do |format|
      format.html { redirect_to cadastros_url, notice: 'Cadastro excluído com sucesso..' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cadastro
      @cadastro = Cadastro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cadastro_params
      params.require(:cadastro).permit(:id_cliente_coelce, :digito_verificador_cliente_coelce, :codigo_ocorrencia, :data_ocorrencia, :valor, :parcelas, :id_cliente_parceira, :codigo_produto, :codigo_empresa_parceira, :livre)
    end
end

luzdohorto/app/helpers/cadastros_helper.rb
module CadastrosHelper
end

luzdohorto/app/views/cadastros/_form.html.erb
<%= form_for(cadastro) do |f| %>
<% if cadastro.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(cadastro.errors.count, "error") %> prohibited this cadastro from being saved:</h2>
  <ul>
    <% cadastro.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<form>
  <br>
  <div class="ls-form row container-fluid">
    <div class="page-header">
      <h1 align="center">Doador</h1>
    </div>
    <br>
    <fieldset>
      <div class="cadastro">
        <div class="row well">
          <label class="ls-label col-md-12">
            <b class="ls-label-text">ID</b>
            <p class="ls-label-info" style="font-size: 12px">Digite o ID do cliente ENEL</p>
            <%= f.number_field :id_cliente_coelce, :max =>9999999999, required: true%>
          </label>
          <label class="ls-label col-md-12">
            <b class="ls-label-text">Digito Verificador</b>
            <p class="ls-label-info" style="font-size: 12px">Digite o dígito verificador do Cliente ENEL</p>
            <%= f.number_field :digito_verificador_cliente_coelce, :max => 9, required: true%>
          </label>
          <label class="ls-label col-md-12">
            <b class="ls-label-text">Código Ocorrência</b>
            <p class="ls-label-info" style="font-size: 12px">Digite o código de ocorrência</p>
            <%= f.number_field :codigo_ocorrencia, :max => 99,required: true %>
          </label>
          <label class="ls-label col-md-12">
            <b class="ls-label-text">Data Ocorrência</b>
            <p class="ls-label-info" style="font-size: 12px">Insira a data de Ocorrência</p>
            <br>
            <%= f.date_select :data_ocorrencia, :order => [:day, :month, :year], :use_month_names=>["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"]%>
          </label>
          <label class="ls-label col-md-12">
            <b class="ls-label-text">Valor</b>
            <p class="ls-label-info" style="font-size: 12px">Dígite o Valor</p>
            <%= f.number_field :valor, :step => 0.01, required: true%>
          </label>
          <label class="ls-label col-md-12 ">
            <b class="ls-label-text">Parcelas</b>
            <p class="ls-label-info" style="font-size: 12px">Dígite o número de Parcelas</p>
            <%= f.number_field :parcelas, required: true%>
          </label>
          <label class="ls-label col-md-12">
            <b class="ls-label-text">Protocolo</b>
            <p class="ls-label-info" style="font-size: 12px">Caso haja, digite o número de protocolo</p>
            <%= f.text_area:livre%>
          </label>
          <label class="ls-label col-md-12">
            <b class="ls-label-text">Colaborador</b>
            <p class="ls-label-info" style="font-size: 12px">Caso haja, selecione</p>
            <%= select("colaborador", "colaborador_id", Colaborador.all.collect {|p| [ p.nomereduzido, p.id ] }, { include_blank: true, prompt: true})  %>
          </label>
          <br>
          <div class="actions" align="center">
            <%= f.submit "Salvar", class:"btn btn-primary"%>
            <%=link_to 'Cancelar', root_path, class: 'btn btn-warning'%>
          </div>
        </fieldset>
      </form>   
    </div>
  </div>

  <% end %>

luzdohorto/app/views/cadastros/_search.html.erb
<center>
<p style="font-size: 20px">Busca</p>
<p>( pelo número do cliente, valor ou número de protocolo )</p>
	<%= form_tag cadastros_path, method: :get, class: 'search' do %>
  		<%= text_field_tag :q, @search_query %> <%= link_to 'Limpar', root_path,class: 'btn btn-default'%>
	<% end %>
</center>

luzdohorto/app/views/cadastros/edit.html.erb
<%= render 'form', cadastro: @cadastro %>

luzdohorto/app/views/cadastros/index.html.erb
<script src="//rawgithub.com/stidges/jquery-searchable/master/dist/jquery.searchable-1.0.0.min.js"></script>
 
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="page-header">
          <h1 align="center">Cadastros</h1>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 col-lg-offset-4" align="right">
        <%= render 'search' %> 
    </div>
  </div>
  <br>
  <br>
  <br>
  <div class="row">
    <div class="col-lg-12">
      <table class="table table-striped">
        <thead>
          <tr>           
            <th>Id Cliente ENEL</th>
            <th>Codigo Ocorrencia</th>
            <th>Valor</th>
            <th>Parcelas</th>
            <%if current_user.role == "admin" %>
            <th>Autor</th>
            <th>Data do Cadastro</th>   
            <th>Protocolo</th>
            <th> </th>
            <th><a href="#" class="btn btn-primary btn-md disabled" role="button" aria-disabled="true">Total de registros <span class="badge"> <%= @cadastros.total_count %> </span></a></th>     
            <% end %>

          </tr>
        </thead>
        <tbody>
          <% @cadastros.each do |cadastro| %>
          <tr style="font-size: 15px">
            <%if current_user.id == cadastro.user_id || policy(@cadastros).index? %>
            <td><%= cadastro.id_cliente_coelce %></td>
            <td><%= cadastro.codigo_ocorrencia %></td>                  
            <td> R$ <%= cadastro.valor %></td>
            <td align="center"><%= cadastro.parcelas %></td>
            <%if current_user.role == "admin"%>
            <td><a href="#" class="btn btn-default btn-xs disabled" role="button" aria-disabled="true"><%= cadastro.user.username%></a></td>
            <td align="center"><%= cadastro.data_ocorrencia.strftime("%d / %m / %Y") %></td>
            <% end %>
            <td align="center" colspan="1"><%= cadastro.livre %></td>
            <td>  </td>
            <td align="center">
              <%= link_to'Ver', cadastro,class: 'btn btn-info btn-sm' %>
              <%= link_to 'Editar', edit_cadastro_path(cadastro),class: 'btn btn-success btn-sm'%>  
            </td>
          
        </tr>

        <% end %>
        <% end %>
      </tbody>
    </table>
  <center><%= paginate @cadastros %></center>
  </div>
</div>

luzdohorto/app/views/cadastros/new.html.erb
<%= render 'form', cadastro: @cadastro %>

luzdohorto/app/views/cadastros/show.html.erb
<div class="cadastro" style="font-size: 15px">
  <div class="page-header"> <br> <br> <h1 align="center"> Informações </h1></div>
  <div class="panel-group">
    <div class="panel panel-primary class">
      <div class="panel-body"><b>Id Cliente:</b>  <%= @cadastro.id_cliente_coelce %> </div>
    </div>
    <div class="panel panel-primary class">
      <div class="panel-body"><b>Digito Verificador Cliente Coelce:</b> <%= @cadastro.digito_verificador_cliente_coelce %></div>
    </div>
    <div class="panel panel-primary class">
      <div class="panel-body"><b>Código Ocorrência:  </b> <%= @cadastro.codigo_ocorrencia %></div>
    </div>
    <div class="panel panel-primary class">
      <div class="panel-body"><b>Data Ocorrência:</b> <%= @cadastro.data_ocorrencia.strftime("%d / %m / %Y")%></div>
    </div>
    <div class="panel panel-primary class">
      <div class="panel-body"><b>Valor:</b> R$ <%= @cadastro.valor %></div>
    </div>
    <div class="panel panel-primary class">
      <div class="panel-body"><b>Parcelas:</b>   <%= @cadastro.parcelas %></div>
    </div>
    <div class="panel panel-primary class">
      <div class="panel-body"><b>Protocolo:</b>  <%= @cadastro.livre %> </i> </div>
    </div>
    <% if !@cadastro.colabs.blank? %>
        <div class="panel panel-primary class">
          <div class="panel-body"><b>Colaborador:</b>  <%= @cadastro.colabs[0].colaborador.nomereduzido %> </i> </div>
        </div>
    <% end %>
    <br>
    <td>
    <center>
      <%=link_to 'Voltar', root_path, class: 'btn btn-info'%>
      <%=link_to 'Cadastrar Novamente', new_cadastro_path, class: 'btn btn-success'%>
      <!-- <% if current_user.role == "admin" %>
      <%= link_to 'Excluir', cadastro_path(@cadastro), class: 'btn btn-danger', method: :delete, data: { confirm: 'Tem certeza que deseja excluir o registro?' } %> -->
    </center>
    </td>
  </div>
</div>

<% end %>