luzdohorto/config/routes.rb
Rails.application.routes.draw do
  resources :colabs
  resources :colaboradors
  resources :instituicos
  get 'cont_users/index'
  get 'cont_users/new'
  get 'cont_users/edit'
  

  post 'savenew', to: 'users#savenew'
  
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  
  resources :cadastros

  resources :relatorios

  match 'download' => 'relatorios#download', via: [:get, :post]
  #post 'download'=> 'relatorios#download'


  root 'cadastros#index'

  #get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

luzdohorto/app/models/colaborador.rb
class Colaborador < ApplicationRecord
  belongs_to :user
  has_many :colabs
  has_many :colaborador, through: :colabs 
  paginates_per 20
end

luzdohorto/app/controllers/colaboradors_controller.rb
class ColaboradorsController < ApplicationController
  before_action :set_colaborador, only: [:show, :edit, :update, :destroy]

  # GET /colaboradors
  # GET /colaboradors.json
  def index
    @colaboradors = Colaborador.joins(:user).all.order("nomecompleto ASC").page params['page']
  end

  # GET /colaboradors/1
  # GET /colaboradors/1.json
  def show
  end

  # GET /colaboradors/new
  def new
    @colaborador = Colaborador.new
  end

  # GET /colaboradors/1/edit
  def edit
  end

  # POST /colaboradors
  # POST /colaboradors.json
  def create
    @colaborador = Colaborador.new(colaborador_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @colaborador.save
        format.html { redirect_to @colaborador, notice: 'Colaborador cadastrado com sucesso.' }
        format.json { render :show, status: :created, location: @colaborador }
      else
        format.html { render :new }
        format.json { render json: @colaborador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colaboradors/1
  # PATCH/PUT /colaboradors/1.json
  def update
    respond_to do |format|
      if @colaborador.update(colaborador_params)
        format.html { redirect_to @colaborador, notice: 'Colaborador atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @colaborador }
      else
        format.html { render :edit }
        format.json { render json: @colaborador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colaboradors/1
  # DELETE /colaboradors/1.json
  def destroy
    @colaborador.destroy
    respond_to do |format|
      format.html { redirect_to colaboradors_url, notice: 'Colaborador excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_colaborador
      @colaborador = Colaborador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def colaborador_params
      params.require(:colaborador).permit(:nomecompleto, :telefone, :endereco, :nomereduzido, :user_id)
    end
end

luzdohorto/app/helpers/colaboradors_helper.rb
module ColaboradorsHelper
end

luzdohorto/app/views/colaboradors/_form.html.erb
<%= form_for(colaborador) do |f| %>
  <% if colaborador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(colaborador.errors.count, "error") %> prohibited this colaborador from being saved:</h2>

      <ul>
      <% colaborador.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form>
  <br>
  <div class="ls-form row container-fluid">
    <div class="page-header">
      <h1 align="center">Colaborador</h1>
    </div>
    <br>
    <fieldset>
      <div class="cadastro">
        <div class="row well">
          <label class="ls-label col-md-12">
            <b class="ls-label-text">Nome Completo</b>
            <%= f.text_field :nomecompleto %>
          </label>
          <label class="ls-label col-md-12">
            <b class="ls-label-text">Telefone</b>
            <%= f.text_field :telefone %>
          </label>
          <label class="ls-label col-md-12">
            <b class="ls-label-text">Endereço</b>
            <%= f.text_field :endereco %>
          </label>
          <label class="ls-label col-md-12">
            <b class="ls-label-text">Nome reduzido</b>
            <%= f.text_field :nomereduzido %>
          </label>
        </div>
      </div>
    </fieldset>


  <div class="actions" align="center">
    <%= f.submit "Salvar", class:"btn btn-primary"%>
    <%= link_to 'Voltar', colaboradors_path, class: "btn btn-success"%>
  </div>
<% end %>

luzdohorto/app/views/colaboradors/edit.html.erb
<%= render 'form', colaborador: @colaborador %>

luzdohorto/app/views/colaboradors/index.html.erb
<div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="page-header">
          <h1 align="center">Colaboradores</h1>
        </div>
      </div>
    </div>
    
   <div class="row">
    <div class="col-lg-40">
      <table class="table table-striped">
         <thead>
            <tr>
              <th>Nome Completo</th>
              <th>Telefone</th>
              <th> </th>
              <th>Nome reduzido</th>                          
            </tr>
          </thead>

          <tbody>
            <% @colaboradors.each do |colaborador| %>
              <tr style="font-size: 15px">
                <td><%= colaborador.nomecompleto %></td>
                
                <td><%= colaborador.telefone %></td>
                <td> </td>
                <td><%= colaborador.nomereduzido %></td>
                
                <td><%= link_to 'Ver', colaborador, class: 'btn btn-info btn-sm' %>
                <%= link_to 'Editar', edit_colaborador_path(colaborador),class: 'btn btn-success btn-sm' %>
                <!-- <%if current_user.role == "admin" %>
                  <%= link_to 'Excluir', colaborador, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' }, class:'btn btn-danger btn-sm' %></td>
                <%end%> -->
              </tr>
            <% end %>
          </tbody>
        </table>
<center><%= paginate @colaboradors %></center>
<br>

<center><%= link_to 'Cadastrar novo Colaborador', new_colaborador_path, class: 'btn btn-primary' %>
  <% if current_user.role == "admin"%>
    <%= link_to 'Relatório dos Colaboradores', colabs_path, class: 'btn btn-default' %>
  <% end %>

</center>

luzdohorto/app/views/colaboradors/new.html.erb
<%= render 'form', colaborador: @colaborador %>

luzdohorto/app/views/colaboradors/show.html.erb
<div class="cadastro" style="font-size: 15px">
  <div class="page-header"> <br> <br> <h1 align="center">Informações do Colaborador </h1></div>
<div class="panel-group">
    <div class="panel panel-primary class">
      <div class="panel-body"><b>Nome Completo: </b> <%= @colaborador.nomecompleto %> </div>
    </div>
    <div class="panel panel-primary class">
      <div class="panel-body"><b>Telefone:</b> <%= @colaborador.telefone %></div>
    </div>
    <div class="panel panel-primary class">
      <div class="panel-body"><b>Endereco: </b> <%= @colaborador.endereco %> </div>
    </div>
    <div class="panel panel-primary class">
      <div class="panel-body"><b>Nome Reduzido: </b> <%= @colaborador.nomereduzido %> </div>
    </div>
    <div class="panel panel-primary class">
      <div class="panel-body"><b>Cadastrado Por: </b> <%= @colaborador.user.username %> </div>
    </div>
    <br>
   <center>
     <td>
        <%= link_to 'Editar', edit_colaborador_path(@colaborador), class:"btn btn-success" %>
        <%= link_to 'Voltar', colaboradors_path, class:"btn btn-warning" %>
     </td>
  </center>
  </div>
</div>