luzdohorto/config/routes.rb
Rails.application.routes.draw do
  resources :colabs
  resources :colaboradors
  resources :instituicos
  get 'cont_users/index'
  get 'cont_users/new'
  get 'cont_users/edit'
  

  post 'savenew', to: 'users#savenew'
  
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  
  resources :cadastros

  resources :relatorios

  match 'download' => 'relatorios#download', via: [:get, :post]
  #post 'download'=> 'relatorios#download'


  root 'cadastros#index'

  #get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

luzdohorto/app/views/layouts/_user_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
      <a class="navbar-brand">  <%= link_to (image_tag("favicon.png")), root_path, class: 'navbar-brand' %></a>      
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li> <%=link_to 'Inicio', root_path%></li>
          <li> <%=link_to 'Cadastrar' , new_cadastro_path%> </li>
          <% if current_user.role == "admin"%>
            <li> <%=link_to 'Usuários', cont_users_index_path%> </li>
            <li> <%=link_to 'Relatórios', relatorios_path%> </li>
            <li> <%=link_to 'Novo Relatório', new_relatorio_path%> </li>
            <li> <%=link_to 'Instituição', instituicos_path%> </li>          
          <% end %>
          <li> <%=link_to 'Colaboradores', colaboradors_path%> </li>              
          <li><%=link_to "Editar Perfil", edit_user_registration_path %></li>
          <li><%=link_to "Sair", destroy_user_session_path, :method => :delete%></li>
        </ul>
      </div>
    </div>
  </nav>

luzdohorto/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Luz do Horto</title>
  
  <link href='https://fonts.googleapis.com/css?family=Audiowide' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Didact Gothic' rel='stylesheet'>
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
  <%= favicon_link_tag 'icon.png' %>
  <%=stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%=javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%=csrf_meta_tags %>
</head>
<% if user_signed_in? %>
   <%= render 'layouts/user_navbar' %>
<% end %>
<body bgcolor="#F2F5A9">
  <div id="content">
    <% if notice.present? %>
     <center><div class="alert alert-success" role="alert" style="width: 700px">
        <p id="notice" style="font-size: 15px"><%= notice %></p>
      </div></center>
    <% end %>
    <% if alert.present? %>
      <center><div class="alert alert-danger" role="alert" style="width: 700px">
        <p id="notice" style="font-size: 15px"><p id="alert"><%= alert %></p>
      </div></center>
    <% end %>

   
  </div>
   <%= yield %>
</body>

    <br>
    <div class="bottom-bar">
      <center>
      <hr class="linha " width="100%">
      Copyright © 2017 NExTI <a href="mailto:webmaster@example.com"><b class="teste">nextipro2@gmail.com</b></a></center>
    </div>
    <div id="topcontrol" title="Scroll Back to Top" style="position: fixed; bottom: 5px; right: 5px; opacity: 1; cursor: pointer;"><i class="fa fa-angle-up"></i></div>
</html>