luzdohorto/config/routes.rb
Rails.application.routes.draw do
  resources :colabs
  resources :colaboradors
  resources :instituicos
  get 'cont_users/index'
  get 'cont_users/new'
  get 'cont_users/edit'
  

  post 'savenew', to: 'users#savenew'
  
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  
  resources :cadastros

  resources :relatorios

  match 'download' => 'relatorios#download', via: [:get, :post]
  #post 'download'=> 'relatorios#download'


  root 'cadastros#index'

  #get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

luzdohorto/app/models/instituico.rb
class Instituico < ApplicationRecord
end

luzdohorto/app/controllers/instituicos_controller.rb
class InstituicosController < ApplicationController
  before_action :set_instituico, only: [:show, :edit, :update, :destroy]

  # GET /instituicos
  # GET /instituicos.json
  def index
    @instituicos = Instituico.all
  end

  # GET /instituicos/1
  # GET /instituicos/1.json
  def show
  end

  # GET /instituicos/new
  def new
    @instituico = Instituico.new
  end

  # GET /instituicos/1/edit
  def edit
  end

  # POST /instituicos
  # POST /instituicos.json
  def create
    @instituico = Instituico.new(instituico_params)

    respond_to do |format|
      if @instituico.save
        format.html { redirect_to @instituico, notice: 'Instituição criada com sucesso.' }
        format.json { render :show, status: :created, location: @instituico }
      else
        format.html { render :new }
        format.json { render json: @instituico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instituicos/1
  # PATCH/PUT /instituicos/1.json
  def update
    respond_to do |format|
      if @instituico.update(instituico_params)
        format.html { redirect_to @instituico, notice: 'Instituico atualizada com sucesso..' }
        format.json { render :show, status: :ok, location: @instituico }
      else
        format.html { render :edit }
        format.json { render json: @instituico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instituicos/1
  # DELETE /instituicos/1.json
  def destroy
    @instituico.destroy
    respond_to do |format|
      format.html { redirect_to instituicos_url, notice: 'Instituico excluída com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instituico
      @instituico = Instituico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instituico_params
      params.require(:instituico).permit(:nome_instituicao, :id_cliente_parceira, :codigo_produto, :codigo_empresa_parceira)
    end
end

luzdohorto/app/helpers/instituicos_helper.rb
module InstituicosHelper
end

luzdohorto/app/views/instituicos/_form.html.erb
<%= form_for(instituico) do |f| %>
  <% if instituico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instituico.errors.count, "error") %> prohibited this instituico from being saved:</h2>

      <ul>
      <% instituico.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<form>
  <br>
  <div class="ls-form row container-fluid">
    <div class="page-header">
      <h2 align="center">Instituição</h2>
    </div>
    <br>
    <fieldset>
      <div class="cadastro">
        <div class="row well">
          <label class="ls-label col-md-12">
            <b class="ls-label-text">Nome Instituição</b>
            <p class="ls-label-info">Digite o nome da Instituição</p>
            <%= f.text_field :nome_instituicao, {:minlength => 20, :maxlength => 20,required: true}%>
          </label>
          <label class="ls-label col-md-12">
            <b class="ls-label-text">Id Cliente Parceiro</b>
            <p class="ls-label-info">Dígite o Id do Cliente Parceiro</p>
            <%= f.number_field :id_cliente_parceira, {in: -1...1000000000, required: true}%>
          </label>
          <label class="ls-label col-md-12">
            <b class="ls-label-text">Código Produto </b>
            <p class="ls-label-info">Insira o Código Produto</p>
            <%= f.number_field :codigo_produto, {in: -1...10000, required: true}%>
          </label>
          <label class="ls-label col-md-12">
            <b class="ls-label-text">Código Empresa Parceira</b>
            <p class="ls-label-info">Dígite o código da empresa parceira</p>
            <%= f.number_field :codigo_empresa_parceira, {in: -1...100, required: true}%>
          </label>
          <br>
          <div class="footer" align="center">
            <%= f.submit "Salvar", class:"btn btn-primary"%>
            <%=link_to 'Cancelar', instituicos_path, class: 'btn btn-warning'%>
          </div>
        </fieldset>
      </form>   
    </div>
  </div>
  <% end %>

luzdohorto/app/views/instituicos/edit.html.erb
<%= render 'form', instituico: @instituico %>

luzdohorto/app/views/instituicos/index.html.erb
<script src="//rawgithub.com/stidges/jquery-searchable/master/dist/jquery.searchable-1.0.0.min.js"></script>
 
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="page-header">
          <h1 align="center">Instituição</h1>
        </div>
      </div>
    </div>
    
  <br>
  <br>
  <br>
  <div class="row">
    <div class="col-lg-12">
      <table class="table table-striped">
        <thead>
          <tr >
          <th>Nome Instituicao</th>
          <th>Id Cliente parceira</th>
          <th>Codigo Produto</th>
          <th>Codigo Empresa Parceira</th>
        </tr>
      </thead>
      <tbody>
        <% @instituicos.each do |instituico| %>
        <tr style="font-size: 15px">
          <td><%= instituico.nome_instituicao %></td>
          <td><%= instituico.id_cliente_parceira %></td>
          <td><%= instituico.codigo_produto %></td>
          <td><%= instituico.codigo_empresa_parceira %></td>
          <td align="center">
            <%= link_to 'Ver', instituico,class: 'btn btn-info btn-sm' %>
            <%= link_to 'Editar', edit_instituico_path(instituico),class: 'btn btn-success btn-sm'%>  
          </td>                
      </tr>      
      <% end %>
    </tbody>
  </table>
  <center><%= link_to 'Cadastrar', new_instituico_path,class: 'btn btn-primary' %></center>
 </div>
</div>

luzdohorto/app/views/instituicos/new.html.erb
<%= render 'form', instituico: @instituico %>

luzdohorto/app/views/instituicos/show.html.erb
<div class="cadastro" style="font-size: 15px">
  <div class="page-header"> <br> <br> <h1 align="center"> Informações </h1></div>
  <div class="panel-group">
     
  	<div class="panel panel-primary class">
      <div class="panel-body"><b>Nome Instituição:</b> <%= @instituico.nome_instituicao %></div>
    </div>
    <div class="panel panel-primary class">
      <div class="panel-body"><b>Id Cliente Parceira:</b> <%= @instituico.id_cliente_parceira %></div>
    </div>
    <div class="panel panel-primary class">
      <div class="panel-body"><b>Código do Produto:</b> <%= @instituico.codigo_produto %></div>
    </div> 
    <div class="panel panel-primary class">
      <div class="panel-body"><b>Código da Empresa Parceira:</b> <%= @instituico.codigo_empresa_parceira %></div>
    </div> 
    <br>
    <td>
      <%=link_to 'Voltar', instituicos_path, class: 'btn btn-info'%> 
      <%= link_to 'Excluir', instituico_path(@instituico), class: 'btn btn-danger', method: :delete, data: { confirm: 'Tem certeza que deseja excluir o registro?' } %>
    </td>
  </div>
</div>